hash-format = "sha256"

[[files]]
file = "config/alexscaves-client.toml"

[[files]]
file = "config/entityculling.json"

[[files]]
file = "config/fml.toml"

[[files]]
file = "config/resourcepackoverrides.json"

[[files]]
file = "config/simple-custom-early-loading.json"

[[files]]
file = "config/simple-custom-early-loading/mojang_bg.png"

[[files]]
file = "mods/3dskinlayers.pw.toml"
metafile = true

[[files]]
file = "mods/DolphinRide-1.2-1.20.1-.jar"

[[files]]
file = "mods/aether-enhanced-extinguishing.pw.toml"
metafile = true

[[files]]
file = "mods/aether-lost-content.pw.toml"
metafile = true

[[files]]
file = "mods/aether.pw.toml"
metafile = true

[[files]]
file = "mods/alexs-caves.pw.toml"
metafile = true

[[files]]
file = "mods/alexs-mobs-interaction.pw.toml"
metafile = true

[[files]]
file = "mods/alexs-mobs-naturalist-compat.pw.toml"
metafile = true

[[files]]
file = "mods/alexs-mobs.pw.toml"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
metafile = true

[[files]]
file = "mods/animal-garden-alligator-gar.pw.toml"
metafile = true

[[files]]
file = "mods/animal-garden-bull-shark.pw.toml"
metafile = true

[[files]]
file = "mods/animal-garden-manatee.pw.toml"
metafile = true

[[files]]
file = "mods/animal-garden-mouse.pw.toml"
metafile = true

[[files]]
file = "mods/animal-garden-porcupine.pw.toml"
metafile = true

[[files]]
file = "mods/animal-garden-prairie-dog.pw.toml"
metafile = true

[[files]]
file = "mods/animal-garden-sea-otter.pw.toml"
metafile = true

[[files]]
file = "mods/animal-garden-spotted-hyena.pw.toml"
metafile = true

[[files]]
file = "mods/animal-garden-western-gorilla.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/aquarius-libs.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/azurelib.pw.toml"
metafile = true

[[files]]
file = "mods/backpacks.pw.toml"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
metafile = true

[[files]]
file = "mods/better-fps-render-distance.pw.toml"
metafile = true

[[files]]
file = "mods/better-snowy-biome.pw.toml"
metafile = true

[[files]]
file = "mods/better-tridents.pw.toml"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
metafile = true

[[files]]
file = "mods/blueprint.pw.toml"
metafile = true

[[files]]
file = "mods/borninchaos.pw.toml"
metafile = true

[[files]]
file = "mods/brutal-bosses-dungeon.pw.toml"
metafile = true

[[files]]
file = "mods/chloride.pw.toml"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
metafile = true

[[files]]
file = "mods/corgilib.pw.toml"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
metafile = true

[[files]]
file = "mods/cosmetic-armor-reworked.pw.toml"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
metafile = true

[[files]]
file = "mods/dolphinride.pw.toml"
metafile = true

[[files]]
file = "mods/domesticationinnovation-1.7.1-cheddfix.jar"

[[files]]
file = "mods/domesticationinnovation.pw.toml"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-ancient-city-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-pillager-outpost-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-stronghold-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-swamp-hut-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
metafile = true

[[files]]
file = "mods/dungeons_delight.pw.toml"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
metafile = true

[[files]]
file = "mods/easy-disenchanting.pw.toml"
metafile = true

[[files]]
file = "mods/easy-villagers.pw.toml"
metafile = true

[[files]]
file = "mods/ecologics.pw.toml"
metafile = true

[[files]]
file = "mods/elemental-creepers.pw.toml"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
metafile = true

[[files]]
file = "mods/falling-tree.pw.toml"
metafile = true

[[files]]
file = "mods/fallingleavesforge.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-cutting-biomes-o-plenty.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
metafile = true

[[files]]
file = "mods/fast-paintings.pw.toml"
metafile = true

[[files]]
file = "mods/faunify.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/findmyfriends-2.0.0.jar"

[[files]]
file = "mods/findmyfriends.pw.toml"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/friends-and-foes-forge.pw.toml"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
metafile = true

[[files]]
file = "mods/gravestone-mod.pw.toml"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
metafile = true

[[files]]
file = "mods/hardcore-revival.pw.toml"
metafile = true

[[files]]
file = "mods/iceandfire-ce.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/immersive_furniture-forge-chedd.jar"

[[files]]
file = "mods/immersivefurniture.pw.toml"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
metafile = true

[[files]]
file = "mods/jupiter.pw.toml"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
metafile = true

[[files]]
file = "mods/lapiz-lazuli-armor-and-tools.pw.toml"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
metafile = true

[[files]]
file = "mods/mimi-mod.pw.toml"
metafile = true

[[files]]
file = "mods/mob-ai-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/mobs-of-mythology.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/monkeyfix-1.0.0.jar"

[[files]]
file = "mods/monkeyfix.pw.toml"
metafile = true

[[files]]
file = "mods/mowzies-mobs.pw.toml"
metafile = true

[[files]]
file = "mods/mucklogo-1.0.0.jar"

[[files]]
file = "mods/mucklogo.pw.toml"
metafile = true

[[files]]
file = "mods/name-tag-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/naturalist.pw.toml"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
metafile = true

[[files]]
file = "mods/oh-the-biomes-weve-gone.pw.toml"
metafile = true

[[files]]
file = "mods/oh-the-trees-youll-grow.pw.toml"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
metafile = true

[[files]]
file = "mods/particular-reforged.pw.toml"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
metafile = true

[[files]]
file = "mods/projectilefix-1.0.0.jar"

[[files]]
file = "mods/projectilefix.pw.toml"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
metafile = true

[[files]]
file = "mods/radium-reforged.pw.toml"
metafile = true

[[files]]
file = "mods/redpandapro-1.0.0.jar"

[[files]]
file = "mods/redpandapro.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/resourcepackcached.pw.toml"
metafile = true

[[files]]
file = "mods/rubidium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/runiclib.pw.toml"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
metafile = true

[[files]]
file = "mods/simple-custom-early-loading.pw.toml"
metafile = true

[[files]]
file = "mods/smart-completion.pw.toml"
metafile = true

[[files]]
file = "mods/smartbrainlib.pw.toml"
metafile = true

[[files]]
file = "mods/spawn-animations.pw.toml"
metafile = true

[[files]]
file = "mods/species.pw.toml"
metafile = true

[[files]]
file = "mods/structory-towers.pw.toml"
metafile = true

[[files]]
file = "mods/structure-gel-api.pw.toml"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
metafile = true

[[files]]
file = "mods/thrasherfix-1.0.0.jar"

[[files]]
file = "mods/thrasherfix.pw.toml"
metafile = true

[[files]]
file = "mods/txnilib.pw.toml"
metafile = true

[[files]]
file = "mods/universal-enchants.pw.toml"
metafile = true

[[files]]
file = "mods/upgrade-aquatic.pw.toml"
metafile = true

[[files]]
file = "mods/uranus.pw.toml"
metafile = true

[[files]]
file = "mods/visuality-forge.pw.toml"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
metafile = true

[[files]]
file = "mods/what-are-they-up-to.pw.toml"
metafile = true

[[files]]
file = "mods/when-dungeons-arise-seven-seas.pw.toml"
metafile = true

[[files]]
file = "mods/when-dungeons-arise.pw.toml"
metafile = true

[[files]]
file = "mods/wildlife-expanded-skunk.pw.toml"
metafile = true

[[files]]
file = "mods/worldeditcui-forge.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/ydms-red-panda.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
metafile = true

[[files]]
file = "readme.md"

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/makeup-ultra-fast-shader.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/potato-shaders.pw.toml"
metafile = true
