hash-format = "sha256"

[[files]]
file = "config/alexscaves-client.toml"
hash = "8f063ba9b9fe3f2e3bce9cb2b5e806ee1d29dfbfdb5de96987219e7b20f6aaf9"

[[files]]
file = "config/entityculling.json"
hash = "062a3e9671dbeab94073c02b85966e85f59d06be556f3f1d6d7812c5467a2904"

[[files]]
file = "config/fml.toml"
hash = "93bad02230893b5667229acafd7a755c438d85ad0230f54e68491a1993e2a24d"

[[files]]
file = "config/resourcepackoverrides.json"
hash = "2edf67757c102780a4ed3c3cb060d7dad42a23555a0821e921553da97521808e"

[[files]]
file = "config/simple-custom-early-loading.json"
hash = "f65e3f94df1eb38fb4502b8e1cf014937672c95e5bbbc80b67777e22e315958b"

[[files]]
file = "config/simple-custom-early-loading/mojang_bg.png"
hash = "6ab2b9a5357c80bd8ec28f0bd5b238a2054816b3d8a21ffc99f158934dcbedb7"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "18b585d0f14984c5548eb9df3d56a5758482615c65db8260ef6038a3c8ee7acc"
metafile = true

[[files]]
file = "mods/DolphinRide-1.2-1.20.1-.jar"
hash = "c0775177d0015d200d105c4074302726ead8f198d733cdcdbc4b2ae96d004a28"

[[files]]
file = "mods/aether-enhanced-extinguishing.pw.toml"
hash = "8e7f2282ce70b5a82bfe05304c30e71d6d3c26a29a75d6e1f31e85af8b86eb2e"
metafile = true

[[files]]
file = "mods/aether-lost-content.pw.toml"
hash = "93dbcd5448e94be7bf618788f380773a1dd95fff06c802b52d7bf85163a66e44"
metafile = true

[[files]]
file = "mods/aether.pw.toml"
hash = "1aaba088a650cc1499e1871cfa92f97e3d10a9d8c612fbd784b36c12382196de"
metafile = true

[[files]]
file = "mods/alexs-caves.pw.toml"
hash = "0cbc4b2c6b58b7a94f030ae84f18057e5dc78a17bad429f40b8884926a6ab233"
metafile = true

[[files]]
file = "mods/alexs-mobs-interaction.pw.toml"
hash = "eb59aec4111989113c5837b02009566b50e42e0e888ebd7633582438019663cc"
metafile = true

[[files]]
file = "mods/alexs-mobs-naturalist-compat.pw.toml"
hash = "4582e0baac124b6ed5fa7117667b4e96bc9c1543763fa0235526bce6fcdc5181"
metafile = true

[[files]]
file = "mods/alexs-mobs.pw.toml"
hash = "e1016eb125a5a41a10f80847eb00affae0e539e703846f303949ed5d82b7f1bf"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "ca3bf1a0e9c493a9a65db0eb1ab411d6894a4f71d815919019f6abf67e25b38a"
metafile = true

[[files]]
file = "mods/animal-garden-alligator-gar.pw.toml"
hash = "0d1ca131c5ae9b19b6fafe0b8b03575b87903af605ef8fc236f36d3dec70731e"
metafile = true

[[files]]
file = "mods/animal-garden-bull-shark.pw.toml"
hash = "0884a01795fb84a7d3672fe0ea2de7d644f628c0d2cca32187657df4a058fa2e"
metafile = true

[[files]]
file = "mods/animal-garden-common-raven.pw.toml"
hash = "f076ec4aad1fe1c2781d91aff63c8066c7f2ce8ed47b6b7fefedc3ec780d8d35"
metafile = true

[[files]]
file = "mods/animal-garden-fennec-fox.pw.toml"
hash = "2625aba8b18a33c2c4486352ce5e1891397942fa72a3c1d379edc9ed072e9dd7"
metafile = true

[[files]]
file = "mods/animal-garden-manatee.pw.toml"
hash = "3da230273da482b43c1bc8708869e9c9bf615882ce2fbf0c49fe8bad664ddfb6"
metafile = true

[[files]]
file = "mods/animal-garden-meerkat.pw.toml"
hash = "22d7fd39ea6b25bebe22d1a8e2cbe5c23bf55532bb2c4d73fe3db7ae8adecdf6"
metafile = true

[[files]]
file = "mods/animal-garden-mouse.pw.toml"
hash = "90bb3147da1183b9232df7d87eeff783c68e8c43ae595219f55217143ac02d82"
metafile = true

[[files]]
file = "mods/animal-garden-porcupine.pw.toml"
hash = "d39bcfab187e2e51eedcd89d89af00516acfb1ea55dc6bde392bdc1736a0363f"
metafile = true

[[files]]
file = "mods/animal-garden-prairie-dog.pw.toml"
hash = "7000c692bff0779eeb871313e20ec1bb122e380bfda5f48cef1a0f0848a580c4"
metafile = true

[[files]]
file = "mods/animal-garden-red-panda.pw.toml"
hash = "175d1f6d8045db88e4dfba31c2999d4eaffa020b33142a5a9b0c9af059655911"
metafile = true

[[files]]
file = "mods/animal-garden-sea-otter.pw.toml"
hash = "07c2383d5d71bb56c95f9627c8a9713b1cf5c13c937c9f37020cc263ad90f993"
metafile = true

[[files]]
file = "mods/animal-garden-spotted-hyena.pw.toml"
hash = "879f6cd31333640ae1532b721d5663636bf0f193c779199ee6be5e3cd8e68a8c"
metafile = true

[[files]]
file = "mods/animal-garden-sugar-glider.pw.toml"
hash = "c9bc97f2e386f0cacd8936c3a473eaf3c4d83f1e0f770bab76e78b699537bc83"
metafile = true

[[files]]
file = "mods/animal-garden-western-gorilla.pw.toml"
hash = "dd7071d46641ac0f61f4a5ef39c089b3f1a30cf904bc4791fff9be3157716918"
metafile = true

[[files]]
file = "mods/animal-garden-white-rhinoceros.pw.toml"
hash = "459f6bc385b7d4ff634bcbc15e446f5d77ba65134660945930c0ff685b596878"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "793693a85f3c87d4e899ee0c58deabc53690bf5a70f17343f28fd5063ce8a1e1"
metafile = true

[[files]]
file = "mods/aquarius-libs.pw.toml"
hash = "1aee7c19f4bf62f59396529abaad6474d9cf0f6fb893e11ab11ad98487df3012"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "4e81241ba2da06f425efc5e09fb6b38470125c1581c39e1310c5843a0b96ec76"
metafile = true

[[files]]
file = "mods/azurelib.pw.toml"
hash = "52af8d3df28fb1c16f4f6c9a49a0dda6ddb8725c6690c36d01a6aca94ec5c6ab"
metafile = true

[[files]]
file = "mods/backpacks.pw.toml"
hash = "c48d4aa0ab31079afdcc831805dbcc00ac6131716d802f90f448f643f71b5a67"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "b8c29dac6fb7c1cf18ca53b7a96c6c4854307999b77a751e803bdd9650a125e0"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "fec49033058ced91f7668d4e305e599f5527501ef37c1f30f96d8927d6202d32"
metafile = true

[[files]]
file = "mods/better-fps-render-distance.pw.toml"
hash = "0651f0e4c8067fbbc25f3efcd1d43278b44d240e4c8e375fb398eaf63e34f58d"
metafile = true

[[files]]
file = "mods/better-snowy-biome.pw.toml"
hash = "8ebdc7ced67be51751419074b5246b02ef74f7163e33de60c284d16eb459b6cb"
metafile = true

[[files]]
file = "mods/better-tridents.pw.toml"
hash = "1321e5c33d7c7b28538ff048ff2e8e47e56a2af1edf21da9953c080383eb5ab2"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "2bcea8e16d358942a8f8b8cf6e39cc303d90fac29b1b3ecb8033bd214d4afa0f"
metafile = true

[[files]]
file = "mods/blueprint.pw.toml"
hash = "90fc66d49d29c1b1a5b14c5d571d628c6853f7f0519b04e74e14399c75cd08c6"
metafile = true

[[files]]
file = "mods/borninchaos.pw.toml"
hash = "7961deef4c56e70d0308f80f043d653eae50e738df824afc256d6f3c3e829912"
metafile = true

[[files]]
file = "mods/chloride.pw.toml"
hash = "2af0c21d9553758fc6cefc92ad9f4ba4c1d8c0edf1b953d8cbb2ddf907a1e814"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
hash = "c7ac7f84731a0ca1fefb3491c3f65c2767afd4be207e094fcb65c4cea99c9549"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "e3dd03e7fec88831974857e2cdded54dd5c5bdcaa3f6d6248c2800e82db4dd41"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "d47260d085f9c59609bbc7582968e60f4c476d934c815142360bbcc4b5113a4d"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "4d5ba0ec7ea7abf0ef76f3f08853bd7c886eec95b1795cbeacaba8bc608e2913"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "8cea6a7ec6b151f92a3a62261530bb1aefe173ad19840c0319aa10e0d8ab2386"
metafile = true

[[files]]
file = "mods/corgilib.pw.toml"
hash = "aab86d52c9896cfcf7c0635c3c897c3dd190de84e3be9eeb726a22c5a61602ed"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "9f2bb57e05bad305f03c25c275c6d11e952835a41b2da68dba10a0bd1f3f6261"
metafile = true

[[files]]
file = "mods/cosmetic-armor-reworked.pw.toml"
hash = "cfa8aa9c0437721dab2057c932c9cf8ec3d3a11f672040601305238d13df85e8"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "9582c04926dd9cea7f68f6f1b4e068bd2ec3f6fcb2734497d885364c6b74b1e1"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "2eb26b157c4159bfeff6a00147afa35284397d558f84b55367d1a41064d7456a"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "9eefd607e0d54ec444e798ccdeede1a09a3939440bd1e11c11b84c07a5134be2"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "47fd33da68d0b13cdffd4124f5bc9cff64caa2878ce7e979ba8092400c2ae1eb"
metafile = true

[[files]]
file = "mods/dolphinride.pw.toml"
hash = "6c31969169bc5af3231c58987a65dcf1eca0e0d79e5a36c9fb221f54073513ed"
metafile = true

[[files]]
file = "mods/domesticationinnovation-1.7.1-cheddfix.jar"
hash = "322d93f6ae899e14ec5b6d7a7450d29ff07094c22d54ba6996ca78b8ec45b797"

[[files]]
file = "mods/domesticationinnovation.pw.toml"
hash = "2559ebb63962d86829c9120d4a97ccf7aafd2b872974cd57016b98c3fb51a830"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-ancient-city-overhaul.pw.toml"
hash = "969c1659c859067215f5e76d716b050bc07e8959ce1f9b377505f95e7c80af14"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-pillager-outpost-overhaul.pw.toml"
hash = "39f5723b02609821dad037669fd0731943dc829860e83439d68f5085b7460243"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-stronghold-overhaul.pw.toml"
hash = "5cedfd0086fef005b7b4a7a305d908d16ccf41c434af93974da280db78ad7e84"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-swamp-hut-overhaul.pw.toml"
hash = "b73799f443bda6d85176d9cfa32b1beda2e2e0a031dd75af86b117c1a59b8534"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
hash = "a6af059766ea70358690d048898d19e493108e2e06a97542fac696fd5e03589a"
metafile = true

[[files]]
file = "mods/dungeons_delight.pw.toml"
hash = "5a9c0b4bb162a8edfd2541b4d30e691b98e389068e5a9c6f9d9b4248ad7a5044"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
hash = "0c91bda0e9a61b15ac8a729678c70af9b9630c8ea6cadf591750b129caa10000"
metafile = true

[[files]]
file = "mods/easy-disenchanting.pw.toml"
hash = "2edd772e45018c5ca53bf3f620a883b88dd59edb54e24bd0ff656bfc8f07a026"
metafile = true

[[files]]
file = "mods/easy-villagers.pw.toml"
hash = "a65613e31ab6db637264a3988a390af659093d349b9a881c79222091461490d4"
metafile = true

[[files]]
file = "mods/ecologics.pw.toml"
hash = "1859de5f388c57e08412a9f9ed2b9069ed8078a963264c0d66cb7eba13938538"
metafile = true

[[files]]
file = "mods/elemental-creepers.pw.toml"
hash = "72487a1563ca991fefdb1b64a93ffd86c2bcc10ed58a647c8081395619a8e5aa"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "5ec0c37f3f4ad07a40c10376668bca80334ddb7ad2bab06eb4de8f7aac339c8e"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "25d3f272639cef595de126a2c51faff793dc03bcde63ef060e1277c315583ce7"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "866b92f2599f2e4058db0fd4583870ace1ad9063e8d3bc71407d3d239bcd1243"
metafile = true

[[files]]
file = "mods/falling-tree.pw.toml"
hash = "c403c22a6334812040538866bc4851f28358c1d8f8b44f029f4c1c82f94ca5e1"
metafile = true

[[files]]
file = "mods/fallingleavesforge.pw.toml"
hash = "2db3a1221517a6d4344b7359463d115461844f12b001edd8d19395eecc12a7f3"
metafile = true

[[files]]
file = "mods/farmers-cutting-biomes-o-plenty.pw.toml"
hash = "94231b261ec4dfbed08035271ecdf099a245cae486a1bed57252a5f081e117e3"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "99876b4f4941ce79c052275c1b10530b1581cc86479c4b0252e9c8b0bc93f8b7"
metafile = true

[[files]]
file = "mods/faunify.pw.toml"
hash = "9996be1eae7b5f1e2747ae9bae7f383971a7b5c079beb577ebfef1878d74f877"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "902bac905b93271f02bd0951a22bac06a3da24f5c237fcaeb469e14a7679e508"
metafile = true

[[files]]
file = "mods/findmyfriends-2.0.0.jar"
hash = "f31b9990d0d6fc154139f08b17c1d0bac11f3ce9ec8834d43e792694a387203f"

[[files]]
file = "mods/findmyfriends.pw.toml"
hash = "d3156e138801e745e364b1126315ebe2b46d24b8594a615d6c2d3c548c4f0457"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "2a2f2168bf03bfa3034ad9583588676c5d66b6f7c767df9fe259ab55350792d2"
metafile = true

[[files]]
file = "mods/friends-and-foes-forge.pw.toml"
hash = "37f1b3f45cb39418f5c309b6d17cf5c2a7038fd1d3dee9619610b83a94db449a"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "0afd150b72f436cbde384b93d099e51fe724ffe82f052d7d19bf00d5a94b8a70"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "1030e18f2e875dfdf39de82b823e1dfe6009f21f1aaad338137d3a90504e2f7e"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "71f185e62d546881244d4b5a213ebc3d2d6df14b0218c0e5dd6426fcb22cb55f"
metafile = true

[[files]]
file = "mods/gravestone-mod.pw.toml"
hash = "df07d5af0d287b944943b65e0b0990dc21fbbad6fee05b9d698a9f62b906ea9c"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "db495b3ac268709a2ba673bfe220b10257fb7dae549f94bfbd539617d571f131"
metafile = true

[[files]]
file = "mods/hardcore-revival.pw.toml"
hash = "01c0d7488838d7ace6360fde1d6bdbcd5066954571e963af4f10cd39669aa6e4"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "2621dfb5b3ad17a3adf927cc92a3bc6b0dd982c32f0265f920b29a61b34d182e"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
hash = "0f83be0761e0014686517c20f2850242152dd7a26e87088d869028bc40a8a125"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "29b62d42548542296d9932bcbb8a93ffba0b75b7cc859a67e596aeb1e048ace2"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "70a4ecd9d0c04ad20aeb976c1ee28933ce48a0a1f43df42deafaeb2ad7235297"
metafile = true

[[files]]
file = "mods/lapiz-lazuli-armor-and-tools.pw.toml"
hash = "29bb1fed28fcec58813a216e796c368ac1bdc45bc5fede8deb9d58536988e282"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "457f1d7c34cb8cb605b002fee89d3f0a766eb461ef82236c48cb1196b1e81a97"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
hash = "0b9cc190139b0eb2d5f0153f05717ed53edd499ad2a3eeee99ea75d22fd0ef1c"
metafile = true

[[files]]
file = "mods/mob-ai-tweaks.pw.toml"
hash = "3859a7d772df6ee863653aec5d12a9fb3e5169be68fa93271ac19b67bda5fd80"
metafile = true

[[files]]
file = "mods/mobs-of-mythology.pw.toml"
hash = "1edb87c9e4f5a904e010df3d83d488519f622be84bc3d724aac1c8264749f36f"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "97b807fbcaa59fd13ffdfd1428a2484d7c320f94af9ffda992ee9be9beba0286"
metafile = true

[[files]]
file = "mods/mowzies-mobs.pw.toml"
hash = "fc09447db9efb9f9ec998ce84cf11edfd089a2515a300e45fd06e607aabc051a"
metafile = true

[[files]]
file = "mods/mucklogo-1.0.0.jar"
hash = "d7cb727fe6cb96d556a270b3ac0b6f19bb5ee33779659f2f57d99fd9b4b3e646"

[[files]]
file = "mods/mucklogo.pw.toml"
hash = "f75b45427743ee19f5027d82854fb387b9da333ef7e36d02f9825069413ff2a5"
metafile = true

[[files]]
file = "mods/name-tag-tweaks.pw.toml"
hash = "b645ddacefcf095b97166479c1be91907627fd844d40fd333a96611961f842bb"
metafile = true

[[files]]
file = "mods/naturalist.pw.toml"
hash = "6039fa77bfd0871c009092508bbaaed5f25947af425943fe3a2c8e6b32cd3102"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "1cfa08f9a882ee2d8dda5680909b9593fdd0467f1166ed1cd5c6413aa6ec93b5"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "f83b253ca6a8e6f2f847952704da0e1fb00e65cbb10b7c9cb15d1a1780618da0"
metafile = true

[[files]]
file = "mods/oh-the-biomes-weve-gone.pw.toml"
hash = "204d6d88b0ea0977b1b878ebf7d52c236aec5c603f115f80af3710283d058f97"
metafile = true

[[files]]
file = "mods/oh-the-trees-youll-grow.pw.toml"
hash = "4b4d83e721458f356072f309058dbdcc5ab490dd41b53764ec6305dcf30a6ed6"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "e3b879b027674a3c9b002eb24f2ea47397bf2087124387f65241b4e0ca4e73d5"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
hash = "7ad7f4a23f347a5949d1bb965bdd91e6f07803c25fe727718fb5155b7cf4b41c"
metafile = true

[[files]]
file = "mods/particular-reforged.pw.toml"
hash = "5f75fbb8f143d973279a41625de4c1d4382c09f7f902e978b67071846a1ef535"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "765987a78e5d8c782d0da2de99998b43b5907d6c41347d3804045ad109e4a586"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "4dd7038889da90e145f9d074bec64a61aaae12dc57c875aa7ad99b8b2e07979b"
metafile = true

[[files]]
file = "mods/radium-reforged.pw.toml"
hash = "77fa86d36ada0d178545853f987f9e71128e1833c9c29ae62c436c09bdb31948"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "5c07edd0c8fe82e85efd6c027476ba54cf98291526803b74614c3436292e4ab6"
metafile = true

[[files]]
file = "mods/resourcepackcached.pw.toml"
hash = "210909880704cdaf7ee4fd757519ccf0755c877722be3cb7347f9d4488295ed4"
metafile = true

[[files]]
file = "mods/rubidium-extra.pw.toml"
hash = "817b4a47826bd99c69957fe07131d5704984f89fec96287cdc20c6fbe46100cf"
metafile = true

[[files]]
file = "mods/runiclib.pw.toml"
hash = "2dbe8c4d2e526717bb37fca847e0d7e42c2f65575e90883b096a2cd2787ccb30"
metafile = true

[[files]]
file = "mods/saddle-crafting-backport.pw.toml"
hash = "b53f840f4a7f8c1da293e1a6891c6f2fd58048e76cc14609ba0e6f0be6628bcf"
metafile = true

[[files]]
file = "mods/simple-custom-early-loading.pw.toml"
hash = "0690c55cf4f6cfe557f926a8b78327f6f63448885cac13e590c43a0ae996dee4"
metafile = true

[[files]]
file = "mods/smart-completion.pw.toml"
hash = "9f17bf8139852fe4c77b10a4d5d71d7d738fb38ca63f70f3c97f78a05f1917b5"
metafile = true

[[files]]
file = "mods/smartbrainlib.pw.toml"
hash = "8d3e9ef52ac3b65fb976629b55652ca30f9ad8b7ff37925c3111ae78386e1a97"
metafile = true

[[files]]
file = "mods/spawn-animations.pw.toml"
hash = "658f2f78263d779d2c988d548b09af015c4ef8e51819acf5f18bb1bfd1c5ee82"
metafile = true

[[files]]
file = "mods/species.pw.toml"
hash = "50d0cb105f5db0a982d9c00f5ea6aee826866576b796526686ab0877c912e968"
metafile = true

[[files]]
file = "mods/structory-towers.pw.toml"
hash = "2d5fddc37293f33e8967e4687a69fb98126a8c4f79194547d1ab6e2941007910"
metafile = true

[[files]]
file = "mods/structure-gel-api.pw.toml"
hash = "0a1893b4abfd0e7243095240b329552c082dd3fa7874b43e9b43c94812875472"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "23c3dddf24d8d65b2ad798247389647b47e10439dca2c46b1c958a8d2b0a1841"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "14117b94c456598c9acece143c7a0da3cf56d13182d035a74a2da8a52dd19cbd"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "3b61fcf1c80cfdd79282be71ddfa9cce02fc13f8d87a760db455e2a97b801f40"
metafile = true

[[files]]
file = "mods/thrasherfix-1.0.0.jar"
hash = "4d4b654ae656ed43347dd977b1e96962af835a361c75cd9abf18cb687089801f"

[[files]]
file = "mods/thrasherfix.pw.toml"
hash = "e63d092e1524b99b97429c5360d7a6a7c0fb6274c9685b3fd8083de4db875510"
metafile = true

[[files]]
file = "mods/txnilib.pw.toml"
hash = "c2df41a37fec3a93afc4e2866705bf9e457d506ce8cd02e61c2f610d4f6a7617"
metafile = true

[[files]]
file = "mods/universal-enchants.pw.toml"
hash = "966bcfb1bb6b3fcd7066e03d37f97df8e443011d5032ab0482ac6a3b9c13eaa6"
metafile = true

[[files]]
file = "mods/upgrade-aquatic.pw.toml"
hash = "909482378bf0ed15645bcbba896daf9e83b7ef4e100bc44d6d3a34090f13578f"
metafile = true

[[files]]
file = "mods/visuality-forge.pw.toml"
hash = "736738062381bec4d55b726546b4fab7443bea0e5983e8af65b90c56da72da06"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "50dfd8547f93d1bc8f31e1740f94e24aadf661cb2948587ac16a41404b10effd"
metafile = true

[[files]]
file = "mods/worldeditcui-forge.pw.toml"
hash = "bc6b6c847c51928cc2a716aca4c3e10bf300643554ee43a8476516adcf801f86"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "0f4c36a62455f7a78f36b8768f2fd980e558d9a18552c6ee00e9d090b51de341"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "134b3cee2ac2b5c5b9d02d8d70e8e4ba32c7c241f5bc51209521831a7c254e22"
metafile = true

[[files]]
file = "shaderpacks/makeup-ultra-fast-shader.pw.toml"
hash = "e569821e398ed298d85515bd362828e622185e25abbc7d3faa3ebef0f81359c7"
metafile = true

[[files]]
file = "shaderpacks/potato-shaders.pw.toml"
hash = "8958fff9fcdff84582c75584b9fd89fed7e2b21f28c6a752857ce1458ffbfd26"
metafile = true
