name = "Joshcraft"
author = "Chedd"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e4983614b72399a29605def4819ae45263707e67b3ce72e4e5913f7b6029c0a"

[versions]
forge = "47.4.15"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
