name = "Joshcraft"
author = "Chedd"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3953b12aff2e17530cb47365a752a29cfb9e65d2ddd0205a37f39655486bfa3e"

[versions]
forge = "47.4.15"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
