name = "Joshcraft"
author = "Chedd"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2a98fbd4cea8b5a7912c2e17f317fa34b155e99fab90b1d30e51dba7fcb7aee"

[versions]
forge = "47.4.15"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
