name = "Joshcraft"
author = "Chedd"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d648a66b0c123179a3fc7f22fd60df807a3a3c37ac3e5d3595de16fe000d13b"

[versions]
forge = "47.4.15"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
