name = "Joshcraft"
author = "Chedd"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50621ca42edfa4285bc7de82e23e1986d3301bf0af405d1a2347dc650b75b641"

[versions]
forge = "47.4.15"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
